[package]
name = "rust-gpu-tools"
version = "0.2.2"
authors = ["Keyvan Kambakhsh <keyvankambakhsh@gmail.com>", "porcuquine <porcuquine@gmail.com>"]
description = "Rust OpenCL tools"
edition = "2018"
homepage = "https://github.com/filecoin-project/rust-gpu-tools"
license = "MIT/Apache-2.0"
repository = "https://github.com/filecoin-project/rust-gpu-tools"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocl = { version = "0.19.4", package = "fil-ocl" }
dirs = "2.0.2"
sha2 = "0.8.2"
thiserror = "1.0.10"
lazy_static = "1.2"
