version: 2.1

executors:
  default:
    docker:
      - image: cimg/rust:1.70
    resource_class: small
  gpu:
    machine:
      image: linux-cuda-12:2023.05.1
    resource_class: gpu.nvidia.small

jobs:
  test:
    executor: gpu
    steps:
      - checkout
      - run:
          name: Install OpenCL
          command: |
            sudo apt update
            sudo apt install ocl-icd-opencl-dev --no-install-recommends --yes
      - run:
          name: Install Rust
          command: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain $(cat rust-toolchain) --profile minimal -y
      - run:
          name: Run tests
          command: cargo test
      - run:
          name: Run `add` example
          command: cargo run --example add

  rustfmt:
    executor: default
    steps:
      - checkout
      - run:
          name: Run cargo fmt
          command: cargo fmt --all -- --check

  clippy:
    executor: default
    steps:
      - checkout
      - run:
          name: Run cargo clippy
          command: cargo clippy --all-features --all-targets -- -D warnings

  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Run cargo release build
          command: cargo build --release

  rustdoc:
    executor: default
    steps:
      - checkout
      - run:
          name: Run rustdoc
          command: cargo rustdoc --all-features -- -D warnings

workflows:
  version: 2.1

  test:
    jobs:
      - rustfmt
      - clippy
      - test
      - build
      - rustdoc
